"""Generate conservative REFramework Lua probes from AccessPlan objects."""

from __future__ import annotations

import json
import re
from typing import Any

from reframework_mcp.metadata import MetadataRepository
from reframework_mcp.models import AccessOperation, AccessPlan, RootKind

_METHOD_SIGNATURE = re.compile(r"^[^:]+::(.+?)\s*->\s*.+$")


def _lua_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _method_selector(canonical: str) -> str:
    match = _METHOD_SIGNATURE.match(canonical)
    if match:
        return match.group(1).strip()
    return canonical.split("::", 1)[-1].split(" ->", 1)[0].strip()


def _member_name(canonical: str) -> str:
    tail = canonical.split("::", 1)[-1]
    return tail.split(":", 1)[0].split(" {", 1)[0].strip()


class LuaDraftService:
    def __init__(self, metadata: MetadataRepository) -> None:
        self.metadata = metadata

    def draft(
        self,
        plan: AccessPlan,
        *,
        mode: str = "read_only",
        emit_targets: bool = True,
    ) -> dict[str, Any]:
        if mode not in {"read_only", "mutation", "hook"}:
            raise ValueError(f"Unsupported probe mode: {mode}")
        lines = [
            "-- Generated by REFramework-MCP 1.0.1",
            f"-- snapshot: {plan.snapshot_id}",
            f"-- plan: {plan.plan_ref}",
            f"-- goal: {plan.goal}",
            "local function require_value(value, label)",
            "    if value == nil then",
            '        error(label .. " is nil")',
            "    end",
            "    return value",
            "end",
            "",
        ]
        assumptions = list(plan.assumptions)
        variables: dict[str, str] = {}
        for node in plan.nodes:
            variable = f"n_{node.node_id}"
            variables[node.node_id] = variable
            input_variable = variables[node.inputs[0]] if node.inputs else None
            generated = self._node_lines(node, variable, input_variable, variables)
            lines.extend(generated)
            if not node.nullable and node.operation is not AccessOperation.BIND_CONSTANT:
                lines.append(f"{variable} = require_value({variable}, {_lua_string(node.node_id)})")
            if node.side_effect == "unknown":
                assumptions.append(f"{node.node_id} may have side effects")
            lines.append("")

        if emit_targets:
            for target in plan.targets:
                lines.append(f"probe.emit({_lua_string(target)}, {variables[target]})")
        lines.append("return true")
        code = "\n".join(lines).rstrip() + "\n"
        unresolved = [
            node.node_id
            for node in plan.nodes
            if node.operation
            in {
                AccessOperation.FILTER,
                AccessOperation.CONSTRUCT_OBJECT,
                AccessOperation.CONSTRUCT_ARRAY,
            }
            and not node.options
        ]
        return {
            "code": code,
            "mode": mode,
            "plan_ref": plan.plan_ref,
            "snapshot_id": plan.snapshot_id,
            "assumptions": sorted(set(assumptions)),
            "unresolved_nodes": unresolved,
        }

    def _node_lines(
        self,
        node: Any,
        variable: str,
        input_variable: str | None,
        variables: dict[str, str],
    ) -> list[str]:
        op = node.operation
        if op is AccessOperation.RESOLVE_ROOT:
            root = node.root
            if root.kind is RootKind.MANAGED_SINGLETON:
                return [f"local {variable} = sdk.get_managed_singleton({_lua_string(root.type_name)})"]
            if root.kind is RootKind.NATIVE_SINGLETON:
                return [f"local {variable} = sdk.get_native_singleton({_lua_string(root.type_name)})"]
            if root.kind is RootKind.STATIC_TYPE:
                return [f"local {variable} = sdk.find_type_definition({_lua_string(root.type_name)})"]
            if root.kind is RootKind.PROVIDED_OBJECT:
                return [f"local {variable} = probe.resolve_object({_lua_string(root.object_ref)})"]
            if root.kind in {RootKind.HOOK_THIS, RootKind.HOOK_ARGUMENT, RootKind.HOOK_RETURN}:
                selector = {
                    RootKind.HOOK_THIS: "this",
                    RootKind.HOOK_ARGUMENT: f"argument:{root.argument_index}",
                    RootKind.HOOK_RETURN: "return",
                }[root.kind]
                return [
                    f"local {variable} = probe.resolve_hook_value("
                    f"{_lua_string(root.hook_ref)}, {_lua_string(selector)})"
                ]
            return [f"local {variable} = probe.resolve_root({_lua_string(root.model_dump_json())})"]

        if op is AccessOperation.RESOLVE_TYPE:
            return [f"local {variable} = sdk.find_type_definition({_lua_string(node.output_type or '')})"]
        if op is AccessOperation.BIND_CONSTANT:
            return [f"local {variable} = {self._literal(node.value)}"]
        if op is AccessOperation.READ_FIELD:
            field_name = _member_name(node.member.canonical_signature)
            return [
                f"local {variable} = require_value({input_variable}, "
                f"{_lua_string(node.inputs[0])}):get_field({_lua_string(field_name)})"
            ]
        if op is AccessOperation.READ_PROPERTY:
            member = self._member(node)
            getter = str(member.get("getter_name") or "")
            if not getter:
                getter = f"get_{member.get('name', _member_name(node.member.canonical_signature))}()"
            elif "(" not in getter:
                getter += "()"
            return [
                f"local {variable} = require_value({input_variable}, "
                f"{_lua_string(node.inputs[0])}):call({_lua_string(getter)})"
            ]
        if op is AccessOperation.CALL_METHOD:
            selector = _method_selector(node.member.canonical_signature)
            arguments = ", ".join(variables[item] for item in node.arguments)
            suffix = f", {arguments}" if arguments else ""
            return [
                f"local {variable} = require_value({input_variable}, "
                f"{_lua_string(node.inputs[0])}):call({_lua_string(selector)}{suffix})"
            ]
        if op is AccessOperation.CALL_STATIC:
            selector = _method_selector(node.member.canonical_signature)
            declaring_type = node.member.canonical_signature.split("::", 1)[0]
            arguments = ", ".join(variables[item] for item in node.arguments)
            suffix = f", {arguments}" if arguments else ""
            type_var = f"{variable}_type"
            method_var = f"{variable}_method"
            return [
                f"local {type_var} = sdk.find_type_definition({_lua_string(declaring_type)})",
                f"local {method_var} = require_value({type_var}, "
                f"{_lua_string(node.node_id + '_type')}):get_method("
                f"{_lua_string(selector)})",
                f"local {variable} = require_value({method_var}, "
                f"{_lua_string(node.node_id + '_method')})(nil{suffix})",
            ]
        if op is AccessOperation.CAST:
            return [f"local {variable} = {input_variable}"]
        if op in {AccessOperation.INDEX, AccessOperation.ITERATE}:
            index = int(node.options.get("index", 0))
            return [
                f"local {variable} = require_value({input_variable}, {_lua_string(node.inputs[0])})[{index}]"
            ]
        if op is AccessOperation.CONSTRUCT_LIST:
            type_name = node.output_type or node.options.get("type_name", "")
            values = ", ".join(variables[item] for item in node.arguments)
            return [f"local {variable} = probe.construct_list({_lua_string(type_name)}, {{{values}}})"]
        if op is AccessOperation.CONSTRUCT_ARRAY:
            type_name = node.output_type or node.options.get("type_name", "")
            values = ", ".join(variables[item] for item in node.arguments)
            return [f"local {variable} = probe.construct_array({_lua_string(type_name)}, {{{values}}})"]
        if op is AccessOperation.CONSTRUCT_DICTIONARY:
            type_name = node.output_type or node.options.get("type_name", "")
            pairs = ", ".join(variables[item] for item in node.arguments)
            return [f"local {variable} = probe.construct_dictionary({_lua_string(type_name)}, {{{pairs}}})"]
        if op is AccessOperation.ASSERT_NON_NULL:
            return [f"local {variable} = require_value({input_variable}, {_lua_string(node.inputs[0])})"]
        if op is AccessOperation.ASSERT_TYPE:
            expected = node.output_type or node.options.get("expected_type", "")
            return [
                f"probe.assert_type({input_variable}, {_lua_string(expected)})",
                f"local {variable} = {input_variable}",
            ]
        if op is AccessOperation.EMIT:
            name = str(node.options.get("name", node.node_id))
            return [
                f"probe.emit({_lua_string(name)}, {input_variable})",
                f"local {variable} = {input_variable}",
            ]
        return [
            f"-- unresolved operation: {op.value}",
            f"local {variable} = {input_variable or 'nil'}",
        ]

    def _member(self, node: Any) -> dict[str, Any]:
        member_id = node.member.member_id
        if member_id is None:
            return {}
        return self.metadata.member_by_pk(member_id, node.member.snapshot_id) or {}

    @staticmethod
    def _literal(value: Any) -> str:
        if value is None:
            return "nil"
        if value is True:
            return "true"
        if value is False:
            return "false"
        if isinstance(value, (int, float)):
            return repr(value)
        if isinstance(value, str):
            return _lua_string(value)
        return _lua_string(json.dumps(value, ensure_ascii=False, sort_keys=True))
